#!/bin/bash


#functions for script
######################
######################

# Makes it quicker and easier for you to create bars in the future.
function bars { echo "===================================="; }

#function that creates variable MY_FEELING
##########################################
function feeling {

	#takes input and defines MY_FEELING variable
	############################################
	read MY_FEELING
	#if user answers good, displays happy message
	#############################################
	case $MY_FEELING in

		[gG]ood)
			clear
			echo
			echo "Glad to hear that!"
			bars
			sleep 2
			;;
	#if user answers bad, displays apology message
	##############################################
		[bB]ad)
			clear
			echo
			echo "I am sorry to hear that!"
			bars
			sleep 2
			;;
	# if user gives undefined answer will ask to try again
	######################################################
		*)
			echo
			echo "I do not understand!"
			echo "Please try again, $MY_NAME!"
			bars
			sleep 2
			feeling
			;;
	esac
}

#function that displays an option list for input
################################################
function optionslist {

	echo "1. Display working directory"
	bars
	sleep 1
	echo
	echo "2. Create new directory named"
	echo "             \"$MY_NAME\"    "
	bars
	sleep 1
	echo
	echo "3. Exit program."
	bars
	echo
	sleep 1
	echo "Please input a number."
	bars
	#input creates INPUT_NUMBER variable
	####################################
	read INPUT_NUMBER
}

#takes variable INPUT_NUMBER and interprets it
##############################################
function options {

	case "$INPUT_NUMBER" in
		1)
			#if input is 1 displays the current working directory
			#and displays a list of directories & files in CWD
			#####################################################
			echo
			sleep 2
			echo "This is your current directory"
			echo "and a list of all contents."
			bars
			sleep 1
			echo
			pwd; sleep 1; echo; ls -lh
			anything
			;;
		2)
			#if input is 2 makes directory on Desktop
			#########################################
			mkdir ~/Desktop/$MY_NAME
 			sleep 1
 			echo "Your directory was made in"
 			echo "the Desktop directory."
 			sleep 1
 			echo "It will be labeled $MY_NAME."
 			bars
 			anything
 			;;
 		3)
			#if input is 3
			#user is prompted to have a great day
			#exits script
			#####################################
			echo "Have a great day $MY_NAME!"
 			sleep 2
			exit
			;;
	esac
}

function anything {

	echo
	echo "Anything else, $MY_NAME?"
	bars
	read INPUT_ADDITION
	if [[ $INPUT_ADDITION = "yes" ]];
	then
		clear
		optionslist
		options
	else
		echo
		echo "Have a wonderful day $MY_NAME!"
		bars
		sleep 2
		exit
	fi

}

#end of functions
#################
#################
#################


#introduction
#############

clear
echo "Hello"
sleep 3
echo
echo
echo "What is your name?"
bars
echo
read MY_NAME
sleep 3
echo
echo
echo "Hello, $MY_NAME - How are you today?"
bars
echo
#asking how user is - uses function feeling
############################################
feeling

#displays date and gives user options on what to do
###################################################
echo
printf "Today is: %(%A, %b %-d, %Y)T\n" -1
bars
sleep 3
echo
echo "What can I do for you, $MY_NAME?"
bars
sleep 1
echo
optionslist
options
echo
echo
sleep 2

